import { useCallback, useEffect, useState } from 'react'
import type { PrintOrderItem, PrintOrderStatus, PrintQueueOrder } from '../../orders/repositories/PrintOrderRepository'
import { createZip } from '../../orders/services/createZip'
import { downloadBlob, downloadUrl } from '../../orders/services/downloadBlob'
import { printOrderRepository } from '../../orders/services/orderServiceInstance'

const statuses: PrintOrderStatus[] = ['Pending', 'Printing', 'Completed', 'Cancelled']
const dateTime = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))

export function AdminPrintQueuePage() {
  const [orders, setOrders] = useState<PrintQueueOrder[]>([]); const [selected, setSelected] = useState<PrintQueueOrder | null>(null)
  const [items, setItems] = useState<PrintOrderItem[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { try { setOrders(await printOrderRepository.listQueue()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load the Print Queue.') } }, [])
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(), 5_000); return () => { window.clearTimeout(initial); window.clearInterval(timer) } }, [load])
  const open = async (order: PrintQueueOrder) => { setSelected(order); setBusy(true); setError(null); try { setItems(await printOrderRepository.listItems(order.id)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to open this order.') } finally { setBusy(false) } }
  const updateStatus = async (status: PrintOrderStatus) => { if (!selected) return; setBusy(true); try { await printOrderRepository.updateStatus(selected.id, status); const next = { ...selected, status }; setSelected(next); setOrders((current) => current.map((order) => order.id === next.id ? next : order)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update status.') } finally { setBusy(false) } }
  const downloadAll = async () => { if (!selected) return; setBusy(true); try { const files = await Promise.all(items.map(async (item, index) => { const response = await fetch(item.imageUrl); if (!response.ok) throw new Error('Unable to download an order image.'); return { name: `${String(index + 1).padStart(2, '0')}.png`, blob: await response.blob() } })); downloadBlob(await createZip(files), `print-order-${selected.id}.zip`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create the ZIP file.') } finally { setBusy(false) } }
  const removeOrder = async () => { if (!selected || !window.confirm('Delete this print order and every uploaded image?')) return; setBusy(true); try { await printOrderRepository.deleteOrder(selected, items); setSelected(null); setItems([]); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to delete this order.') } finally { setBusy(false) } }

  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-violet-600">Production</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Print Queue</h1><p className="mt-2 text-stone-500">Submitted customer orders, newest first.</p></div><button className="min-h-11 rounded-xl border border-stone-200 bg-white px-4 font-semibold" onClick={() => void load()} type="button">Refresh</button></div>
    {error ? <p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700" role="alert">{error}</p> : null}
    <div className="mt-7 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-stone-100 text-xs uppercase tracking-wide text-stone-400"><tr><th className="p-4">Phone Number</th><th>Room</th><th>Order Time</th><th>Images</th><th>Status</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{orders.map((order) => <tr className="border-b border-stone-100 last:border-0" key={order.id}><td className="p-4 font-bold">{order.phoneNumber}</td><td>{order.roomName}</td><td>{dateTime(order.submittedAt)}</td><td>{order.totalImages}</td><td><span className="rounded-full bg-stone-100 px-3 py-1 font-semibold">{order.status}</span></td><td className="p-4 text-right"><button className="min-h-10 rounded-xl bg-stone-950 px-4 font-bold text-white" onClick={() => void open(order)} type="button">Open Order</button></td></tr>)}</tbody></table>{!orders.length ? <p className="p-8 text-center text-stone-500">No submitted print orders.</p> : null}</div>
    {selected ? <section className="mt-7 rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-violet-600">Order {selected.id}</p><h2 className="mt-1 text-2xl font-bold">{selected.phoneNumber} · {selected.roomName}</h2></div><div className="flex flex-wrap gap-2"><select aria-label="Order status" className="min-h-11 rounded-xl border border-stone-200 bg-white px-3 font-semibold" disabled={busy} onChange={(event) => void updateStatus(event.target.value as PrintOrderStatus)} value={selected.status}>{statuses.map((status) => <option key={status}>{status}</option>)}</select><button className="min-h-11 rounded-xl bg-stone-950 px-4 font-bold text-white disabled:opacity-40" disabled={busy || !items.length} onClick={() => void downloadAll()} type="button">Download All (ZIP)</button><button className="min-h-11 rounded-xl bg-rose-50 px-4 font-bold text-rose-700 disabled:opacity-40" disabled={busy} onClick={() => void removeOrder()} type="button">Delete Order</button></div></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item, index) => <article className="rounded-2xl border border-stone-100 p-3" key={item.id}><img alt={`${item.templateName ?? 'Template'} print preview`} className="aspect-square w-full rounded-xl bg-stone-100 object-contain" src={item.imageUrl} /><div className="mt-3 flex items-center justify-between gap-2"><div><p className="font-bold">{item.templateName ?? `Image ${index + 1}`}</p><p className="text-xs text-stone-500">Image {index + 1}</p></div><button className="min-h-10 rounded-xl bg-stone-100 px-3 text-sm font-bold" onClick={() => void downloadUrl(item.imageUrl, `${String(index + 1).padStart(2, '0')}.png`)} type="button">Download</button></div></article>)}</div>
    </section> : null}
  </div>
}
