import { usePathname } from '../../../hooks/usePathname'
import { useAdminTemplates } from '../store/AdminTemplateContext'

const updatedTime = new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' })

export function AdminTemplatesPage() {
  const store = useAdminTemplates()
  const { navigate } = usePathname()

  return <div><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Templates</h1><p className="mt-1 text-stone-500">Create, publish, archive, and maintain print layouts.</p></div><button className="min-h-12 rounded-xl bg-stone-950 px-5 font-semibold text-white" onClick={() => navigate('/admin/templates/new')} type="button">New template</button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{store.templates.map((record) => <article className="overflow-hidden rounded-2xl bg-white shadow-sm" key={record.id}><div className="grid aspect-[16/9] place-items-center bg-stone-100">{record.coverUrl || record.template.thumbnailUrl ? <img alt="" className="h-full w-full object-cover" src={record.coverUrl ?? record.template.thumbnailUrl ?? ''} /> : <span className="text-sm text-stone-400">No cover</span>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{record.template.name}</h2><p className="mt-1 text-xs text-stone-500">{record.info.category} · {record.template.slotCount} slots</p><p className="mt-1 text-[11px] text-stone-400">Updated {updatedTime.format(new Date(record.updatedAt))}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${record.status === 'published' ? 'bg-emerald-100 text-emerald-700' : record.status === 'archived' ? 'bg-stone-200 text-stone-500' : 'bg-amber-100 text-amber-700'}`}>{record.status}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><button className="min-h-10 rounded-lg bg-stone-950 text-sm font-semibold text-white" onClick={() => navigate(`/admin/templates/${record.id}`)} type="button">Edit</button><button className="min-h-10 rounded-lg bg-stone-100 text-sm font-semibold" onClick={() => store.duplicate(record.id)} type="button">Duplicate</button><button className="min-h-10 rounded-lg bg-stone-100 text-sm font-semibold" onClick={() => store.setStatus(record.id, 'published')} type="button">Publish</button><button className="min-h-10 rounded-lg bg-stone-100 text-sm font-semibold" onClick={() => store.setStatus(record.id, 'archived')} type="button">Archive</button><button className="col-span-2 min-h-10 rounded-lg text-sm font-semibold text-rose-600 hover:bg-rose-50" onClick={() => { if (window.confirm(`Delete ${record.template.name}?`)) store.remove(record.id) }} type="button">Delete</button></div></div></article>)}</div></div>
}
