import { useState } from 'react'
import { usePathname } from '../../../hooks/usePathname'
import { canvasPresets, createAdminTemplateRecord } from '../model/templateFactory'
import type { CanvasPreset } from '../model/templateFactory'
import { useAdminTemplates } from '../store/AdminTemplateContext'

export function AdminCreateTemplatePage() {
  const store = useAdminTemplates(); const { navigate } = usePathname()
  const [name, setName] = useState('Untitled Template'); const [preset, setPreset] = useState<CanvasPreset>('a4-portrait'); const [width, setWidth] = useState(2480); const [height, setHeight] = useState(3508)
  const create = async () => { const record = createAdminTemplateRecord(name.trim() || 'Untitled Template', preset, { width: Math.max(100, width), height: Math.max(100, height) }); try { await store.save(record); navigate(`/admin/templates/${record.id}`) } catch (error) { window.alert(error instanceof Error ? error.message : 'Template creation failed.') } }
  return <div className="mx-auto max-w-2xl"><button className="text-sm font-semibold text-stone-500" onClick={() => navigate('/admin/templates')} type="button">← Templates</button><div className="mt-5 rounded-[2rem] bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-violet-600">New printable template</p><h1 className="mt-2 text-3xl font-black">Create template</h1><div className="mt-7 grid gap-5"><label className="text-sm font-bold">Template name<input className="mt-2 min-h-12 w-full rounded-xl border border-stone-200 px-4 font-normal" onChange={(event) => setName(event.target.value)} value={name} /></label><fieldset><legend className="text-sm font-bold">Canvas preset</legend><div className="mt-2 grid gap-2 sm:grid-cols-3">{([['a4-portrait', canvasPresets['a4-portrait'].label], ['a4-landscape', canvasPresets['a4-landscape'].label], ['custom', 'Custom']] as const).map(([id, label]) => <button aria-pressed={preset === id} className={`min-h-20 rounded-2xl border px-3 font-bold ${preset === id ? 'border-violet-600 bg-violet-50 text-violet-700' : 'border-stone-200'}`} key={id} onClick={() => setPreset(id)} type="button">{label}<span className="mt-1 block text-xs font-normal text-stone-400">{id === 'custom' ? 'Your dimensions' : `${canvasPresets[id].width} × ${canvasPresets[id].height}px`}</span></button>)}</div></fieldset>{preset === 'custom' ? <div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold">Width (px)<input className="mt-2 min-h-12 w-full rounded-xl border border-stone-200 px-3 font-normal" min="100" onChange={(event) => setWidth(Number(event.target.value))} type="number" value={width} /></label><label className="text-sm font-bold">Height (px)<input className="mt-2 min-h-12 w-full rounded-xl border border-stone-200 px-3 font-normal" min="100" onChange={(event) => setHeight(Number(event.target.value))} type="number" value={height} /></label></div> : null}<div className="rounded-xl bg-stone-100 p-4 text-sm text-stone-600"><strong className="text-stone-950">300 DPI print canvas</strong><br />A4 Portrait defaults to 2480 × 3508 pixels.</div><button className="min-h-14 rounded-2xl bg-stone-950 px-5 font-bold text-white" onClick={create} type="button">Create Template</button></div></div></div>
}
